# Copyright 2022 Primihub
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


version: 1.0

node: "node0"
location: "127.0.0.1"
grpc_port: 50050

# node_keypair:
#     public_key:
#     private_key:

# load datasets
datasets:
  - description: "train_party_0_data_self"
    model: "csv"
    source: "data/falcon/dataset/MNIST/train_data_A" 
  - description: "train_party_0_label_self"
    model: "csv"
    source: "data/falcon/dataset/MNIST/train_labels_A"
  - description: "train_party_0_data_next"
    model: "csv"
    source: "data/falcon/dataset/MNIST/train_data_B" 
  - description: "train_party_0_label_next"
    model: "csv"
    source: "data/falcon/dataset/MNIST/train_labels_B" 
  - description: "train_party_0"
    model: "csv"
    source: "/tmp/train_party_0.csv" 
  - description: "test_party_0"
    model: "csv"
    source: "/tmp/test_party_0.csv" 

    # Dataset authorization
    # authorization:
    #   - node:
    #     task:

# p2p paramaters
p2p:
  bootstrap_nodes:
    - "/ip4/127.0.0.1/tcp/10080/ipfs/QmYp9xmGgjVzJomWfEe87EPrVSY6jjAV5MMCWCCn4Fqu2A"
  multi_addr: "/ip4/127.0.0.1/tcp/8886"



